name: Terraform checks
on: [push, pull_request]

jobs:
  terraform-linter:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init-bastion
        run: |
          cd modules/terraform-zscc-bastion-azure
          terraform init   

      - name: Terraform Validate
        id: validate-bastion
        run: |
          cd modules/terraform-zscc-bastion-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zscc-ccvm
        run: |
          cd modules/terraform-zscc-ccvm-azure
          terraform init   

      - name: Terraform Validate
        id: validate-zscc-ccvm
        run: |
          cd modules/terraform-zscc-ccvm-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zscc-identity
        run: |
          cd modules/terraform-zscc-identity-azure
          terraform init   

      - name: Terraform Validate
        id: validate-zscc-identity
        run: |
          cd modules/terraform-zscc-identity-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zscc-lb
        run: |
          cd modules/terraform-zscc-lb-azure
          terraform init   

      - name: Terraform Validate
        id: validate-zscc-lb
        run: |
          cd modules/terraform-zscc-lb-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zscc-network
        run: |
          cd modules/terraform-zscc-network-azure
          terraform init   

      - name: Terraform Validate
        id: validate-zscc-network
        run: |
          cd modules/terraform-zscc-network-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zscc-nsg
        run: |
          cd modules/terraform-zscc-nsg-azure
          terraform init   

      - name: Terraform Validate
        id: validate-zscc-nsg
        run: |
          cd modules/terraform-zscc-nsg-azure
          terraform validate -no-color

      - name: Terraform Init
        id: init-zscc-workload
        run: |
          cd modules/terraform-zscc-workload-azure
          terraform init   

      - name: Terraform Validate
        id: validate-zscc-workload
        run: |
          cd modules/terraform-zscc-workload-azure
          terraform validate -no-color
